### ISSUE TITLE
Weird successfull parsing of invalid path literals

### ISSUE THREAD

**Issue by sternenseemann** [nix-community/rnix-parser#148] opened 2022-10-15 15:43 UTC
### Describe the bug

Was messing around with invalid tilde starting path literals:

* `~foo` is parsed to `Ident(Ident(NODE_IDENT@2..4))`, the `~` seemingly disappears into nowhere. The ident is retained as `oo`, i.e. in tvix you can evaluate `let oo = 42; in ~foo`. This literal should be a parse failure.
* `~foo/bar` is parsed to `Path(Path(NODE_PATH@2..8))`, yielding the path `oo/bar`. This should also be a parse failure.

Nix forbids home path literals that don't start with `~/`, so both expressions are invalid Nix. Probably significant out two chars are dropped from the literals and `~/` is also two chars long.

**Comment by tazjin** [comment] 2022-10-15 15:45
I'm guessing this is a duplicate of #146. It should be possible to have rnix report these as errors

**Closed** 2024-12-21 00:45 UTC
Labels: bug
